from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select
from selenium.webdriver.common import action_chains, keys 
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import time

def explara(Event_Post):
	driver = webdriver.Firefox()
	driver.get("https://www.explara.com/a/login")
	time.sleep(5)
	element = driver.find_element_by_name('username')
	element.send_keys(Event_Post.login_id)
	element = driver.find_element_by_name('password')
	element.send_keys(Event_Post.password)
	element = driver.find_element_by_xpath('//input[@value = "login"]')
	element.click()
	time.sleep(10)
	driver.get("https://www.explara.com/create-event")
	time.sleep(5)
	element = driver.find_element_by_name('eventTitle')
	element.send_keys(Event_Post.event_title)
	time.sleep(2)
	driver.execute_script('document.getElementById("detailedLocationFields").style = "display:block;"')
	time.sleep(5)
	element= driver.find_element_by_name('venueName')
	element.send_keys(Event_Post.venue)
	element = driver.find_element_by_name('addr1')
	element.send_keys(Event_Post.address_line_1)
	element = driver.find_element_by_name('addr2')
	element.send_keys(Event_Post.address_line_2)
	element = driver.find_element_by_name('country')
	element.click()
	element = driver.find_element_by_xpath('//option[@value = "India"]')
	element.click()
	time.sleep(10)
	element = driver.find_element_by_name('state_name1')
	element.click()
	element.send_keys(Event_Post.state)
	element = driver.find_element_by_name('city_name2')
	element.send_keys(Event_Post.city)
	element = driver.find_element_by_name('postal')
	element.send_keys(Event_Post.postal)
	s_date = str(Event_Post.start_date[6:]) + '-' + str(Event_Post.start_date[0:2])+ '-'+ str(Event_Post.start_date[3:5])
	driver.execute_script('document. getElementsByName("startDate")[0].value = "'+s_date+'"')

	element = driver.find_element_by_name('startTime')
	element.clear()
	element.send_keys(Event_Post.start_time)
	e_date = str(Event_Post.end_date[6:]) + '-' + str(Event_Post.end_date[0:2])+ '-'+ str(Event_Post.end_date[3:5])
	driver.execute_script('document.getElementsByName("endDate")[0].value = "'+e_date+'"')
	#driver.execute_script('document.getElementsByName("endDate").value = "2015-10-02"')
	element = driver.find_element_by_name('endTime')
	element.clear()
	element.send_keys(Event_Post.end_time)
	element = driver.find_element_by_name('aboutEvent')
	element.send_keys('test test test test test test test test test test test test test test test test test test test test test test test test ')
	element = driver.find_element_by_xpath('//label[@class = "private-radio"]')
	element.click()
	time.sleep(5)
	driver.execute_script('document.getElementsByClassName("form-group event-name")[1].style = "display: block;"')
	element = driver.find_element_by_name('orgName')
	element.clear()
	element.send_keys('Venturesity')
	element = driver.find_element_by_name('orgEmail')
	element.clear()
	element.send_keys('shubham@venturesity.com')
	element = driver.find_element_by_name('orgContactNo')
	element.clear()
	element.send_keys('9002193961')
	element = driver.find_element_by_name('category')
	element.send_keys('technology')
	element = driver.find_element_by_name('orgContactNo')
	element.click()
	time.sleep(10)
	element = driver.find_element_by_xpath('//div[@id = "topicsList"]')
	driver.execute_script('document.getElementById("topicDiv_software").value = "software"')
	driver.execute_script('document.getElementById("topicDiv_software").name = "topics[]"')
	driver.execute_script('document.getElementById("topicDiv_hackathon").value = "hackathon"')
	driver.execute_script('document.getElementById("topicDiv_hackathon").name = "topics[]"')
	driver.execute_script('document.getElementById("topicDiv_programming").value = "programming"')
	driver.execute_script('document.getElementById("topicDiv_programming").name = "topics[]"')
	time.sleep(5)

	driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
	time.sleep(10)
	element = driver.find_element_by_xpath('//button[@id = "topicDivBtn_mobile_technology"]/following::button[2]')
	time.sleep(10)
	element.click()
	#element = driver.find_element_by_xpath('//a[@class = "btn btn-yellow"]/following::span[2]')
	element = driver.find_element_by_link_text('Preview')
	time.sleep(10)
	element.click()







